
services:
  web:
    container_name: motorland_app   # TODO: chang me for new instance
    build: .
#    image: "traefik/whoami"
    environment:
      SHOPIFY_APP_URL: "https://ml.cpro-server.de"
      HOST: "0.0.0.0"
      SHOPIFY_API_KEY: "ca1e1c3d0c4afdd264ed55f280e21d29"
      SHOPIFY_API_SECRET: "dfef16e2eb08e1adbc43543a36429974"
      SCOPES: "write_products,write_orders,read_orders"
      DATABASE_URL: "mysql://root:oY8io2Shshoo9Eix@motorland_db:3306/motorland" # TODO: change me for new instance
    labels:
      - traefik.enable=true
      - traefik.http.routers.ml.rule=Host(`ml.cpro-server.de`) # TODO: change me for new instance
      - traefik.http.routers.ml.entrypoints=websecure
      - traefik.http.routers.ml.tls.certresolver=letsencrypt
 #   - traefik.http.services.ebike.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - web
      - intern
# might be needed, but seems to work without
#    dns:
#      - 8.8.8.8
  db:
    container_name: motorland_db # TODO: change me for new instance
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - ../databaseData/motorland:/var/lib/mysql  # TODO: change me for new instnaces
    environment:
      - MARIADB_INITDB_SKIP_TZINFO=true
        #  - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=oY8io2Shshoo9Eix  # TODO: you may change me
    networks:
      - intern

networks:
  web:
    external: true
  intern:
    external: false
